### PR TITLE
Use bind_to if wagtail 2.5 or later

### LINKED ISSUE #11: Doesn't work on newer Wagtail versions
The edit handler calls `bind_to_model(model)` but new syntax is `bind_to(model=model)`.

The full error is:
```
AttributeError
'ObjectList' object has no attribute 'bind_to_model'
```

and the culprit is in views.py.

### PR DESCRIPTION
**Pull request by rinti**
Fixes #11

### CODE REVIEW

**Comment by seb-b** [comment]
Thanks for the pull request, it might be time to bite the bullet and make the new minimum version of wagtail 2.5 for this package but this will do in the meantime :smiley:

**Comment by seb-b** [comment]
Released in 0.5.2

File: wagtaillinkchecker/views.py [hunk 1]
```diff
@@ -31,7 +31,11 @@
 @lru_cache()
 def get_edit_handler(model):
     panels = extract_panel_definitions_from_model_class(model, ['site'])
-    return ObjectList(panels).bind_to_model(model)
+
+    if WAGTAIL_VERSION >= '2.5':
```
Comment (PresidentNick) [inline wagtaillinkchecker/views.py:35]: This does not work with 2.10 because it seems to be comparing as floats maybe? So 2.10 = 2.1 and 2.1 < 2.5, but really 2.10 > 2.5

Comment (rinti) [reply wagtaillinkchecker/views.py:35]: It's comparing strings and '2.5' is > '2.10' when comparing them. The if-check should probably be removed in favor of not supporting < 2.6 in my opinion.

Comment (seb-b) [reply wagtaillinkchecker/views.py:35]: Yep this has come up now in a few of our packages, the minimum should be raised but the easiest work-around I've seen is in this pr: https://github.com/neon-jungle/wagtailvideos/pull/43/files
